package com.apollo29.ahoy.repository;

import com.opencsv.CSVWriter;
import com.orhanobut.logger.Logger;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.List;

public class CSVRepository {

    private final static String[] FOOTER = new String[]{"List generated by Ahoy! App -"};  // todo add link to app

    public static void csv(OutputStream file, String[] header, List<String[]> data) throws IOException {
        Logger.d("csv output");
        Logger.d(data);
        CSVWriter writer=null;
        writer = new CSVWriter(new PrintWriter(file), ',');
        writer.writeNext(header);
        writer.writeAll(data);
        writer.writeNext(FOOTER);
        writer.close();
    }
}
